image: docker:git

stages:
  - test
  - build
  - deploy

variables:
  ALI_REGISTRY_HOST: "registry.cn-shenzhen.aliyuncs.com"
  ALI_REGISTRY_IMAGE: "registry.cn-shenzhen.aliyuncs.com/ebag/ebag-paper-admin"
  ALI_SERVICE_NAME: "ebag-prod_paper-admin"
  TEST_SERVICE_NAME: "ebag-test_paper-admin"

build-test:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg APP_ROOT=/go/src/$CI_PROJECT_NAME -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA -f docker/test/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  only:
    - test
 
deploy-test:
  stage: deploy
  variables:
    DOCKER_HOST: $DOCKER_HOST_TEST
    DOCKER_TLS_VERIFY: 1
    SERVICE_NAME: test
  image: docker:latest
  script:
    - mkdir -p ~/.docker
    - echo "$DOCKER_HOST_TLS_CA_CERT_TEST" > ~/.docker/ca.pem
    - echo "$DOCKER_HOST_TLS_CERT_TEST" > ~/.docker/cert.pem
    - echo "$DOCKER_HOST_TLS_KEY_TEST" > ~/.docker/key.pem
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA &&　docker service update --image $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA $TEST_SERVICE_NAME
  only:
    - test

build-ali:
  stage: build
  script:
    - docker login -u $ALI_REGISTRY_USER -p $ALI_REGISTRY_PASSWORD $ALI_REGISTRY_HOST
    - docker build --build-arg APP_ROOT=/go/src/$CI_PROJECT_NAME -t $ALI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $ALI_REGISTRY_IMAGE:latest -f docker/prod/Dockerfile .
    - docker push $ALI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $ALI_REGISTRY_IMAGE:latest
  only:
    - tags

deploy-ali:
  stage: deploy
  variables:
    DOCKER_HOST: $DOCKER_HOST_ALI
    DOCKER_TLS_VERIFY: 1
  image: tmaier/docker-compose:latest
  script:
    - mkdir -p ~/.docker
    - echo "$DOCKER_HOST_TLS_CA_CERT_ALI" > ~/.docker/ca.pem
    - echo "$DOCKER_HOST_TLS_CERT_ALI" > ~/.docker/cert.pem
    - echo "$DOCKER_HOST_TLS_KEY_ALI" > ~/.docker/key.pem
    - docker login -u $ALI_REGISTRY_USER -p $ALI_REGISTRY_PASSWORD $ALI_REGISTRY_HOST
    - docker service update --image $ALI_REGISTRY_IMAGE:$CI_COMMIT_TAG $ALI_SERVICE_NAME
  only:
    - tags
